<?php

require_once '../Comment.php';

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-04-29 at 02:01:30.
 */
class CommentTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Comment
     */
    protected $cmnt;
    protected $validTrue1;
    protected $validTrue2;
    protected $validFalse;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {

        $this->cmnt = new Comment('', '', 0, '', 0);
        $this->validTrue1 = new Comment('hello world', '29/04/17', 1, 'cmaher', 0);
        $this->validTrue2 = new Comment('waffle world', '29/04/17', 2, 'cmaher', 0);
        $this->validFalse = new Comment('world world', '29/04/17', 3, 'cmaher', 0);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Comment::__destruct
     * @todo   Implement test__destruct().
     */
    public function test__destruct() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Comment::getComment
     * @todo   Implement testGetComment().
     */
    public function testGetComment() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Comment::getDate
     * @todo   Implement testGetDate().
     */
    public function testGetDate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Comment::getUserid
     * @todo   Implement testGetUserid().
     */
    public function testGetUserid() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Comment::getUsername
     * @todo   Implement testGetUsername().
     */
    public function testGetUsername() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Comment::getVotes
     * @todo   Implement testGetVotes().
     */
    public function testGetVotes() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Comment::setComment
     * @todo   Implement testSetComment().
     */
    public function testSetComment() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Comment::setDate
     * @todo   Implement testSetDate().
     */
    public function testSetDate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Comment::setUserid
     * @todo   Implement testSetUserid().
     */
    public function testSetUserid() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Comment::setUsername
     * @todo   Implement testSetUsername().
     */
    public function testSetUsername() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Comment::setVotes
     * @todo   Implement testSetVotes().
     */
    public function testSetVotes() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Comment::validate
     * @todo   Implement testValidate().
     */
    public function testValidate() {

        $words = ['hello', 'goodbye', 'waffle', 'bird'];

        $prohibited1 = $this->cmnt->validate($this->validTrue1->comment, $words);
        $this->assertTrue($prohibited1);

        $prohibited2 = $this->cmnt->validate($this->validTrue2->comment, $words);
        $this->assertTrue($prohibited2);

        $prohibited3 = $this->cmnt->validate($this->validFalse->comment, $words);
        $this->assertFalse($prohibited3);
    }

}
